package awsig

import (
	"bytes"
	"fmt"
	"net/http/httptest"
	"reflect"
	"testing"
	"time"
)

func TestCanonicalQuery(t *testing.T) {
	v := new(V4[struct{}])
	for _, tc := range []struct{ query, want string }{
		{"", ""},
		{"a=1&a=2", "a=1&a=2"},
		{"a=2&a=1", "a=1&a=2"},
		{"a=0&b=2&b=1", "a=0&b=1&b=2"},
		{"z=1&%C3%A9=2", "%C3%A9=2&z=1"},
		{"a=z&a=%C3%A9", "a=%C3%A9&a=z"},
		{"a-=1&a=2", "a=2&a-=1"},
		{"acl&prefix=a+b", "acl=&prefix=a%20b"},
	} {
		t.Run(tc.query, func(t *testing.T) {
			r := httptest.NewRequest("GET", "https://example.com/?"+tc.query, nil)
			query := r.URL.Query()
			got := v.canonicalRequestHash(r, query, []string{"host"}, unsignedPayload)
			want := sha256Hash([]byte("GET\n/\n" + tc.want + "\nhost:example.com\n\nhost\nUNSIGNED-PAYLOAD"))
			if !bytes.Equal(got, want) {
				t.Fatalf("canonical query should be %q", tc.want)
			}
			if !reflect.DeepEqual(query, r.URL.Query()) {
				t.Fatal("query was mutated")
			}
		})
	}
}

func TestCanonicalHeaders(t *testing.T) {
	v := new(V4[struct{}])
	for _, tc := range []struct {
		name   string
		values []string
		want   string
	}{
		{"repeated", []string{"first", "second"}, "first,second"},
		{"whitespace", []string{"  a  b  c  "}, "a b c"},
		{"tab", []string{"a\tb"}, "a\tb"},
		{"non-breaking space", []string{"a\u00a0b"}, "a\u00a0b"},
		{"surrounding whitespace", []string{"\t\u00a0foo\u00a0\t"}, "foo"},
		{"combined", []string{" a  b ", " c "}, "a b,c"},
		{"empty value", []string{"", "c"}, ",c"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := httptest.NewRequest("GET", "https://example.com/", nil)
			for _, v := range tc.values {
				r.Header.Add("X-Amz-Meta-Test", v)
			}
			original := r.Header.Clone()
			got := v.canonicalRequestHash(r, nil, []string{"host", "x-amz-meta-test"}, unsignedPayload)
			want := sha256Hash([]byte("GET\n/\n\nhost:example.com\nx-amz-meta-test:" + tc.want + "\n\nhost;x-amz-meta-test\nUNSIGNED-PAYLOAD"))
			if !bytes.Equal(got, want) {
				t.Fatalf("canonical header value should be %q", tc.want)
			}
			if !reflect.DeepEqual(original, r.Header) {
				t.Fatal("headers were mutated")
			}
		})
	}
}

func TestCanonicalURI(t *testing.T) {
	v := NewV4[struct{}](nil, V4Config{Service: "s3"})
	for _, path := range []string{"/bucket/a%2Fb", "/bucket/a%2fb", "/bucket/a%20b", "/bucket/a+b", "/bucket/a%2Bb", "/bucket/a%252Fb", "/bucket//a/../b"} {
		t.Run(path, func(t *testing.T) {
			r := httptest.NewRequest("GET", "https://example.com"+path, nil)
			got := v.canonicalRequestHash(r, nil, []string{"host"}, unsignedPayload)
			want := sha256Hash([]byte("GET\n" + path + "\n\nhost:example.com\n\nhost\nUNSIGNED-PAYLOAD"))
			if !bytes.Equal(got, want) {
				t.Fatalf("canonical URI should be %q", path)
			}
		})
	}
}

func TestVerifySDKCanonicalURI(t *testing.T) {
	// Signatures generated by aws-sdk-go-v2 v1.43.0 SignHTTP, with
	// DisableURIPathEscaping enabled for S3, as its client configures it.
	// Keep these independent of our canonicalization implementation.
	for _, tc := range []struct{ service, path, signature string }{
		{"s3", "/a+b", "225f4e2079e61227ccdba08df221fa5c7c76dcedf648b91f9471011b223fdb20"},
		{"s3", "/a:b", "b471458beff10522e9e67f415f56620aeea90a002beea1f62a9f9f530a646dbc"},
		{"s3", "/a%2Fb", "55de8320a013c86ef42fbfd5deac0ff94701824aa9595bac781195959575c8ed"},
		{"s3", "/a%20b", "1a72e944dab0b8db84588a1be70c0f316032d9710087454669b6f9ba0021dfc7"},
		{"execute-api", "/a+b", "6357d6ffc9301d9f1117d578239e876ccca6e8e9ecd404a7ccc4c08b45b29ab7"},
		{"execute-api", "/a:b", "b5b917932189b84e0e90f9a826e8ad6b98850f763c3fa3631be90a720c0c4a3d"},
		{"execute-api", "/a%2Fb", "e42c79cc03742e2a584cd013556c90ae9bbf89f372c68f717252e9931f537007"},
		{"execute-api", "/a%20b", "e88fd7cbc726b5f0ad2cb122a2a2b0cafa959129edca73ae9491d077d0d4de79"},
	} {
		t.Run(tc.service+tc.path, func(t *testing.T) {
			provider := simpleCredentialsProvider{accessKeyID: "key", secretAccessKey: "secret"}
			v := NewV4(provider, V4Config{Region: "us-east-1", Service: tc.service})
			v.now = dummyNow(2026, time.September, 24, 12, 0, 0)
			r := httptest.NewRequest("GET", "https://example.com"+tc.path, nil)
			r.Header.Set("X-Amz-Date", "20260924T120000Z")
			r.Header.Set("X-Amz-Content-Sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")
			r.Header.Set("Authorization", fmt.Sprintf("AWS4-HMAC-SHA256 Credential=key/20260924/us-east-1/%s/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=%s", tc.service, tc.signature))
			if _, err := v.Verify(r); err != nil {
				t.Fatalf("SDK-signed request rejected: %v", err)
			}
		})
	}
}
